name: Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  windows:
    strategy:
      matrix:
        arch: ["e2k"]
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v3

      - name: make largeboards
        run: cd src && make clean && make -j build COMP=mingw ARCH=${{ matrix.arch }} EXE=bookgen-largeboards_${{ matrix.arch }}.exe largeboards=yes && strip bookgen-largeboards_${{ matrix.arch }}.exe

      - uses: actions/upload-artifact@v3
        with:
          name: bookgen
          path: src/bookgen*.exe